### ISSUE TITLE
Could not load NIB in bundle

### ISSUE THREAD

**Issue by silversurfer147** [kf99916/TimelineTableViewCell#10]
Hello, I am trying to use this library, unfortunately it doesn't work. I am beginner in swift, so I suppose, it will be some silly mistake. I have create view with tableview and swift file TimelineViewController. I have copied the code from your demo project (from TimelineTableViewController). When I am trying to run it on simulator, I get error 

`Could not load NIB in bundle: 'NSBundle </Users/silversurfer/Library/Developer/CoreSimulator/Devices/17FBAA4A-F887-4D71-9CD6-41D3979F4A0A/data/Containers/Bundle/Application/14C5257D-7D3E-40CA-9D46-C7E16C0DACF8/Time.app/Frameworks/TimelineTableViewCell.framework> (loaded)' with name 'TimelineTableViewCell''` 

Could someone help me, where I made a mistake? Thank you in advance

**Comment by irfanpule** [comment]
How do you solve this issue ? I get same error?

**Comment by changtraisitinh** [comment]
I also see this issue, anyone help?
