### ISSUE TITLE
Separator TableView

### ISSUE THREAD

**Issue by silversurfer147** [kf99916/TimelineTableViewCell#11]
Hello, I would like to ask about separators. If I want to use separator between cells there is a problem with right margin. The separator ends in the edge of display (check photo). However left side is OK. Is there any way, how to edit properties of this separator? 
<img width="422" alt="snimka obrazovky 2018-11-19 o 19 15 31" src="https://user-images.githubusercontent.com/34755521/48726465-b939ef80-ec2f-11e8-89fe-3c2fbde3cc32.png">

**Comment by kf99916** [comment]
This is the default table view separator style after iOS 11, not handled by this library.
Please check it out for more details: [https://useyourloaf.com/blog/table-view-separator-inset/ ]( https://useyourloaf.com/blog/table-view-separator-inset/)
