### ISSUE TITLE
How can I customize cell?

### ISSUE THREAD

**Issue by SamaritanMachine** [kf99916/TimelineTableViewCell#8]
I want to customize the custom cell. For example, I want to add a location icon and location label in some cells. Also, I need a button in every cells. Can you help?

**Comment by kf99916** [comment]
Sorry for late reply.
Here is the cell's customization: https://github.com/kf99916/TimelineTableViewCell#timelinetableviewcell-1
If they are not what you need, it means the current version does not support. It is very welcome to pull request.
