### ISSUE TITLE
allow leftMargin to change

### ISSUE THREAD

**Issue by muhasturk** [kf99916/TimelineTableViewCell#9]
lets change protection level of attribute named 'leftMargin' internal to public, in order to make change x index of vertical line.

**Comment by kf99916** [comment]
It's a good idea. could you help this issue? Thanks.

**Comment by albarq** [comment]
true ... leftMargin has to be fully controlled by user ...

**Comment by kf99916** [comment]
Fixed by the commit 678eea138d9078e381b7d09c75faec4068b39a13
